# Generated by Django 3.2 on 2022-12-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0002_delete_likecount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dislikecount',
        ),
    ]
