# Generated by Django 3.2 on 2022-12-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('count', '0003_delete_dislikecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='dlc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField()),
                ('dlcount', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='lc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField()),
                ('lcount', models.CharField(max_length=10)),
            ],
        ),
    ]
